name: Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Do build job
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        msbuild -t:SysIo461 -p:Configuration=Release -p:Platform="Any CPU"
        msbuild -t:SysIo -p:Configuration=Release -p:Platform="Any CPU"
