name: Test
on: push
jobs:
  J1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build and run test suite
      run: dotnet test -c Debug TestCore